### ISSUE TITLE
segfault when activating mkgmap created gmapsupp.img

### ISSUE THREAD

**Issue by sebastic** [Maproom/qmapshack#209]
As reported by ael in [Debian Bug #962622](https://bugs.debian.org/962622):
> Trying to read a gmapsupp.img generated by mkgmap using mapnik.typ results in an immediate crash.

The issue can be reproduced with: [test.img](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=962622;filename=test.img;msg=22) (20MB)

gdb shows:
```
Reading symbols from qmapshack...
Reading symbols from /usr/lib/debug/.build-id/07/5f5d5d547e0fdbb95fbe456ab2798f70f317f4.debug...
(gdb) run
Starting program: /usr/bin/qmapshack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffde9b1700 (LWP 467644)]
[New Thread 0x7fffd6289700 (LWP 467645)]
2020-06-11 18:14:33.621 [warning] "no file found for translations '/usr/share/qmapshack/translations/qmapshack_en' (using default)."
[New Thread 0x7fffcffff700 (LWP 467646)]
[New Thread 0x7fffcf17b700 (LWP 467647)]
[Detaching after fork from child process 467648]
[New Thread 0x7fffce97a700 (LWP 467649)]
[New Thread 0x7fffce179700 (LWP 467650)]
[New Thread 0x7fffcd978700 (LWP 467651)]
[New Thread 0x7fffcd177700 (LWP 467652)]
[New Thread 0x7fffcc976700 (LWP 467653)]
[New Thread 0x7fffb7fff700 (LWP 467654)]
[New Thread 0x7fffb77fe700 (LWP 467655)]
[New Thread 0x7fffb6ffd700 (LWP 467656)]
[New Thread 0x7fffb67fc700 (LWP 467657)]
[New Thread 0x7fffb5ffb700 (LWP 467658)]
[New Thread 0x7fffb57fa700 (LWP 467659)]
[New Thread 0x7fff93fff700 (LWP 467661)]
[New Thread 0x7fffb4ff9700 (LWP 467660)]
[New Thread 0x7fff937fe700 (LWP 467662)]
2020-06-11 18:14:34.279 [warning] Empty filename passed to function
2020-06-11 18:14:34.288 [warning] Empty filename passed to function
2020-06-11 18:14:34.345 [warning] Empty filename passed to function
[New Thread 0x7fff92ffd700 (LWP 467663)]
[New Thread 0x7fff927fc700 (LWP 467664)]
[New Thread 0x7fff91ffb700 (LWP 467665)]
[New Thread 0x7fff917fa700 (LWP 467666)]
[New Thread 0x7fff90ff9700 (LWP 467667)]
[New Thread 0x7fff63fff700 (LWP 467668)]
[Thread 0x7fff917fa700 (LWP 467666) exited]
[Thread 0x7fff91ffb700 (LWP 467665) exited]
[Thread 0x7fff90ff9700 (LWP 467667) exited]
[Thread 0x7fff63fff700 (LWP 467668) exited]
[New Thread 0x7fff63fff700 (LWP 467669)]
2020-06-11 18:14:34.490 [warning] Empty filename passed to function
[New Thread 0x7fff90ff9700 (LWP 467670)]
[Thread 0x7fff90ff9700 (LWP 467670) exited]
[New Thread 0x7fff90ff9700 (LWP 467671)]
[Thread 0x7fff90ff9700 (LWP 467671) exited]
[New Thread 0x7fff90ff9700 (LWP 467672)]
[Thread 0x7fff90ff9700 (LWP 467672) exited]
[New Thread 0x7fff90ff9700 (LWP 467673)]
[Thread 0x7fff90ff9700 (LWP 467673) exited]
[New Thread 0x7fff90ff9700 (LWP 467674)]
[Thread 0x7fff90ff9700 (LWP 467674) exited]
[New Thread 0x7fff90ff9700 (LWP 467676)]
[Thread 0x7fff90ff9700 (LWP 467676) exited]

Thread 1 "qmapshack" received signal SIGSEGV, Segmentation fault.
0x00007ffff4b5a0af in QTextCodec::toUnicode(QByteArray const&) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) bt full
#0  0x00007ffff4b5a0af in QTextCodec::toUnicode(QByteArray const&) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#1  0x0000555555a399af in CGarminTyp::parsePolygon (this=<optimized out>, in=..., polygons=...) at ./src/qmapshack/map/garmin/CGarminTyp.cpp:507
        str = {d = 0x55555703d540}
        len = 148
        n = <optimized out>
        t8 = 0 '\000'
        hasTextColor = <optimized out>
        ctyp = <optimized out>
        r = 224 '\340'
        b = 223 '\337'
        property = <optimized out>
        t16_1 = 64
        typ = <optimized out>
        hasLocalization = <optimized out>
        g = 223 '\337'
        t16_2 = 2
        subtyp = <optimized out>
        offset = <optimized out>
        xpmDay = <incomplete type>
        xpmNight = <incomplete type>
        langcode = 0 '\000'
        element = <optimized out>
        tainted = false
        codec = <optimized out>
        N = <optimized out>
#2  0x0000555555a38954 in CGarminTyp::decode (this=this@entry=0x7fffffffb850, array=..., polygons=..., polylines=..., drawOrder=..., points=...) at ./src/qmapshack/map/garmin/CGarminTyp.cpp:56
        in = {d = {d = 0x0}, dev = 0x555556ad2d50, owndev = true, noswap = true, byteorder = QDataStream::LittleEndian, ver = 11, q_status = QDataStream::Ok}
        descriptor = 156
#3  0x00005555559f86ac in CMapIMG::setupTyp (this=0x7fffd800bc00) at ./src/qmapshack/map/CMapIMG.cpp:463
        file = {<QFile> = {<No data fields>}, static cnt = 1, mapped = 0x7fffd47a3800 "\234", mappedSections = {q_hash = {{d = 0x555557126df0, e = 0x555557126df0}}}}
        array = {d = 0x555556cf5820}
        typ = {_vptr.CGarminTyp = 0x5555560a48e8 <vtable for CGarminTyp+16>, version = 1, codepage = 0, year = 3920, month = 5 '\005', day = 8 '\b', hour = 21 '\025', minutes = 28 '\034', seconds = 39 '\'', fid = 1, pid = 6324, 
          sectPoints = {dataOffset = 8735, dataLength = 18172, arrayOffset = 26907, arrayModulo = 4, arraySize = 536}, sectPolylines = {dataOffset = 4987, dataLength = 3592, arrayOffset = 8579, arrayModulo = 4, arraySize = 156}, 
          sectPolygons = {dataOffset = 156, dataLength = 4619, arrayOffset = 4775, arrayModulo = 4, arraySize = 212}, sectOrder = {dataOffset = 0, dataLength = 0, arrayOffset = 27443, arrayModulo = 5, arraySize = 305}, languages = {
            q_hash = {{d = 0x55555711abd0, e = 0x55555711abd0}}}}
        subfile = <optimized out>
#4  0x00005555559fa5e8 in CMapIMG::CMapIMG (this=0x7fffd800bc00, filename=..., parent=<optimized out>) at ./src/qmapshack/map/CMapIMG.cpp:143
        e = <optimized out>
#5  0x0000555555a073d8 in CMapItem::activate (this=0x55555708dc30) at ./src/qmapshack/map/CMapItem.cpp:173
        lock = {val = 93825004138257}
        fi = {d_ptr = {d = 0x5555571a38d0}}
#6  0x0000555555a079ef in CMapItem::toggleActivate (this=0x55555708dc30) at ./src/qmapshack/map/CMapItem.cpp:124
        lock = {val = 93825004138257}
#7  0x0000555555a0cbc7 in CMapList::slotActivate (this=0x555556a7e200) at ./src/qmapshack/map/CMapList.cpp:161
        item = <optimized out>
        activated = <optimized out>
#8  0x00007ffff4b274e8 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#9  0x00007ffff553d812 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#10 0x00007ffff553fe52 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#11 0x00007ffff56c14e2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#12 0x00007ffff56c8b5a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#13 0x00007ffff56c9b82 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#14 0x00007ffff5585776 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#15 0x00007ffff56cc173 in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#16 0x00007ffff5543c32 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#17 0x00007ffff554d3e3 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#18 0x00007ffff4afca52 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#19 0x00007ffff554c4f3 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#20 0x00007ffff55a19c4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#21 0x00007ffff55a3ec4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--
No symbol table info available.
#22 0x00007ffff5543c32 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#23 0x00007ffff554d190 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#24 0x00007ffff4afca52 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#25 0x00007ffff4edba13 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#26 0x00007ffff4edd26b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#27 0x00007ffff4eb7ecb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#28 0x00007fffdf528cda in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
No symbol table info available.
#29 0x00007fffea78360d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#30 0x00007fffea783890 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#31 0x00007fffea78391f in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#32 0x00007ffff4b527c1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#33 0x00007ffff4afb6db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#34 0x00007ffff56c67bd in QMenu::exec(QPoint const&, QAction*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#35 0x0000555555a0c5d2 in CMapList::slotContextMenu (this=0x555556a7e200, point=...) at ./src/qmapshack/map/CMapList.cpp:235
        item = <optimized out>
        itemIsSelected = <optimized out>
        itemIsActivated = <optimized out>
        p = {xp = 97, yp = 302}
#36 0x00007ffff4b274e8 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#37 0x00007ffff556bc75 in QWidget::customContextMenuRequested(QPoint const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#38 0x00007ffff558641e in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#39 0x00007ffff56319ce in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#40 0x00007ffff57af5fe in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#41 0x00007ffff581c2db in QTreeView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#42 0x00007ffff4afc763 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#43 0x00007ffff5543c21 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#44 0x00007ffff554dffb in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#45 0x00007ffff4afca52 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#46 0x00007ffff55a162a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#47 0x00007ffff55a3ec4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#48 0x00007ffff5543c32 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#49 0x00007ffff554d190 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#50 0x00007ffff4afca52 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#51 0x00007ffff4edba13 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#52 0x00007ffff4edd26b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#53 0x00007ffff4eb7ecb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#54 0x00007fffdf528cda in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
No symbol table info available.
#55 0x00007fffea78360d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#56 0x00007fffea783890 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
--Type <RET> for more, q to quit, c to continue without paging--
#57 0x00007fffea78391f in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#58 0x00007ffff4b527c1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#59 0x00007ffff4afb6db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#60 0x00007ffff4b03182 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#61 0x00005555556e6d6e in main (argc=<optimized out>, argv=<optimized out>) at ./src/qmapshack/main.cpp:83
        app = <incomplete type>
        env = <optimized out>
        seed = <optimized out>
        s = {<QObject> = {<No data fields>}, server = 0x555556709110, serverName = {static null = {<No data fields>}, d = 0x555556709820}}
        splash = <optimized out>
        w = {<QMainWindow> = {<No data fields>}, <Ui::IMainWindow> = {<Ui_IMainWindow> = {actionAddMapView = 0x55555698cb10, actionShowScale = 0x55555698cb90, actionSetupMapFont = 0x555556985f40, actionShowGrid = 0x555556985720, 
              actionSetupGrid = 0x5555569edcd0, actionFlipMouseWheel = 0x555556ce8fe0, actionSetupMapPaths = 0x555556bfd740, actionPOIText = 0x5555569c1e30, actionNightDay = 0x555556aa00e0, actionMapToolTip = 0x555556985f90, 
              actionSetupDEMPaths = 0x5555569916c0, actionAbout = 0x5555569c2130, actionWiki = 0x555556985640, actionSetupMapView = 0x55555698aae0, actionLoadGISData = 0x5555569876e0, actionSaveGISData = 0x5555569876c0, 
              actionSetupTimeZone = 0x555556c7d840, actionAddEmptyProject = 0x5555569bcce0, actionGeoSearch = 0x555556981490, actionCloseAllProjects = 0x555556986960, actionSetupUnits = 0x555556991740, 
              actionSetupWorkspace = 0x5555569bcf10, actionImportDatabase = 0x55555698ba60, actionVrtBuilder = 0x555556987dc0, actionStoreView = 0x555556c31c70, actionLoadView = 0x5555569beeb0, actionProfileIsWindow = 0x5555569bd130, 
              actionClose = 0x5555569867b0, actionCloneMapView = 0x55555698aa60, actionCreateRoutinoDatabase = 0x55555698d5b0, actionPrintMap = 0x555556c41d30, actionSetupCoordFormat = 0x555556686ef0, 
              actionSetupMapBackground = 0x555556c7be00, actionSetupWaypointIcons = 0x555556986c50, actionCloseTab = 0x555556ce3ad0, actionQuickstart = 0x555556c67ea0, actionSetupToolbar = 0x555556988610, 
              actionToggleDocks = 0x55555698d270, actionFullScreen = 0x555556986580, actionShowMinMaxTrackLabels = 0x555556cc0250, actionStartQMapTool = 0x5555569be130, actionRenameView = 0x555556ce38a0, 
              actionTrackInfo = 0x5555569edc30, actionShowTrackInfoTable = 0x555556a77f30, actionShowTrackSummary = 0x555556bea1c0, actionShowMinMaxSummary = 0x555556988430, actionShowTrackProfile = 0x555556c23c50, 
              actionTakeScreenshot = 0x555556987050, actionShowTrackInfoPoints = 0x555556987110, actionShowTrackHighlight = 0x55555698cb30, actionHelp = 0x555556c43b80, centralwidget = 0x55555698a9b0, verticalLayout = 0x55555698b1f0, 
              tabWidget = 0x555556991440, menubar = 0x55555698d3b0, menuFile = 0x55555695e1a0, menuView = 0x55555695e320, menuWindow = 0x55555695e500, menu = 0x555556975360, menuProject = 0x5555569756b0, menuExtra = 0x5555569950c0, 
              statusbar = 0x555556975780, dockMaps = 0x555556a465c0, dockWidgetContents = 0x555556afed00, verticalLayout_2 = 0x555556b5a7d0, tabMaps = 0x555556a1a8c0, dockDem = 0x555556a99860, dockWidgetContents_3 = 0x555556a49a00, 
              verticalLayout_3 = 0x555556a49b60, tabDem = 0x555556b90f60, dockWorkspace = 0x555556b8a910, dockWidgetContents_2 = 0x555556b7d170, toolBar = 0x555556b7d3e0, dockDatabase = 0x555556b7ef00, 
              dockWidgetContents_4 = 0x555556babf20, dockRte = 0x555556c9f840, dockWidgetContents_6 = 0x555556c96620, verticalLayout_4 = 0x555556bac170, widget_2 = 0x555556afa360, dockRealtime = 0x555556aeae80, 
              dockWidgetContents_5 = 0x555556c42910}, <No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff5a424e0 <QMainWindow::staticMetaObject>, stringdata = 0x555555b66180 <qt_meta_stringdata_CMainWindow>, 
              data = 0x555555b65ca0 <qt_meta_data_CMainWindow>, static_metacall = 0x5555556eba90 <CMainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, id = 962398829, 
          static pSelf = 0x7fffffffdc00, static homeDir = {d_ptr = {d = 0x55555611da70}}, static mapsPath = {static null = {<No data fields>}, d = 0x55555611dba0}, static demPath = {
            static null = <same as static member of an already seen type>, d = 0x55555611dbd0}, static routinoPath = {static null = <same as static member of an already seen type>, d = 0x55555611dc00}, static brouterPath = {
            static null = <same as static member of an already seen type>, d = 0x55555611dc30}, static databasePath = {static null = <same as static member of an already seen type>, d = 0x55555611dc60}, static gpxPath = {
            static null = <same as static member of an already seen type>, d = 0x55555611dca0}, static paths = {q_hash = {{d = 0x55555611dcd0, e = 0x55555611dcd0}}}, lblPosWGS84 = 0x555557218b30, lblElevation = 0x555557219330, 
          lblSlope = 0x555557219a80, lblPosGrid = 0x55555721a250, mapFont = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff52e76c0, data = 0x7ffff52e7400, static_metacall = 0x0, relatedMetaObjects = 0x0, 
                extradata = 0x0}}, d = {d = 0x555556a21970}, resolve_mask = 131071}, widgetGisWorkspace = 0x555556c585d0, widgetGisDatabase = 0x555556a5fa70, widgetRtWorkspace = 0x555556cc5bf0, toolBarConfig = 0x555556c3d250, 
          geoSearchConfig = 0x555557224200, geoSearchWeb = 0x555556a58560, wptIconManager = 0x555556c391b0, docks = {<QListSpecialMethods<QDockWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {
                      _q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x55555721afa0}, d = 0x55555721afa0}}, 
          activeDocks = {<QListSpecialMethods<QDockWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, 
                  alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff4bda760 <QListData::shared_null>}, d = 0x7ffff4bda760 <QListData::shared_null>}}, displayMode = {i = 2}, dockStates = {d = 0x555556ae3de0}, 
          menuVisible = false, static mutex = {<QBasicMutex> = {d_ptr = {_q_value = {_M_b = {_M_p = 0x0}}}}, <No data fields>}, help = {wp = {d = 0x0, value = 0x0}}}
```

This is from qmapshack (1.14.1-1) on Debian unstable.

Interestingly it works correctly with the gmapsupp files from garmin.openstreetmap.nl.

**Comment by wthaem** [comment]
See QMS-204. Typ file supplied with map has code page 0!

**Comment by sebastic** [comment]
This is indeed a duplicate of #204, closing accordingly.

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
